name: Update GitHub Stats with Private Repos

on:
  schedule:
    - cron: '0 */6 * * *' # setiap 6 jam
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Stats
        run: |
          echo "![GitHub Stats](https://github-readme-stats.vercel.app/api?username=Epangssss&show_icons=true&count_private=true&cache_seconds=3600&token=${{ secrets.GH_STATS_TOKEN }})" > README.md
