name: Update README

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jojoee/github-profile-activity-generator@latest
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
